// Generated by components discovery
declare module 'vue' {
  export interface GlobalComponents {
    'Avis': typeof import("../components/Avis.vue")['default'],
    'CtaAvis': typeof import("../components/CtaAvis.vue")['default'],
    'FullHero': typeof import("../components/FullHero.vue")['default'],
    'GridHero': typeof import("../components/GridHero.vue")['default'],
    'HIcon': typeof import("../components/HIcon.vue")['default'],
    'ProductCard': typeof import("../components/ProductCard.vue")['default'],
    'TFooter': typeof import("../components/TFooter.vue")['default'],
    'TNavBar': typeof import("../components/TNavBar.vue")['default'],
    'NuxtWelcome': typeof import("../node_modules/@nuxt/ui-templates/dist/templates/welcome.vue")['default'],
    'NuxtLayout': typeof import("../node_modules/nuxt/dist/app/components/layout")['default'],
    'NuxtErrorBoundary': typeof import("../node_modules/nuxt/dist/app/components/nuxt-error-boundary")['default'],
    'ClientOnly': typeof import("../node_modules/nuxt/dist/app/components/client-only")['default'],
    'ServerPlaceholder': typeof import("../node_modules/nuxt/dist/app/components/server-placeholder")['default'],
    'NuxtLink': typeof import("../node_modules/nuxt/dist/app/components/nuxt-link")['default']
    'LazyAvis': typeof import("../components/Avis.vue")['default'],
    'LazyCtaAvis': typeof import("../components/CtaAvis.vue")['default'],
    'LazyFullHero': typeof import("../components/FullHero.vue")['default'],
    'LazyGridHero': typeof import("../components/GridHero.vue")['default'],
    'LazyHIcon': typeof import("../components/HIcon.vue")['default'],
    'LazyProductCard': typeof import("../components/ProductCard.vue")['default'],
    'LazyTFooter': typeof import("../components/TFooter.vue")['default'],
    'LazyTNavBar': typeof import("../components/TNavBar.vue")['default'],
    'LazyNuxtWelcome': typeof import("../node_modules/@nuxt/ui-templates/dist/templates/welcome.vue")['default'],
    'LazyNuxtLayout': typeof import("../node_modules/nuxt/dist/app/components/layout")['default'],
    'LazyNuxtErrorBoundary': typeof import("../node_modules/nuxt/dist/app/components/nuxt-error-boundary")['default'],
    'LazyClientOnly': typeof import("../node_modules/nuxt/dist/app/components/client-only")['default'],
    'LazyServerPlaceholder': typeof import("../node_modules/nuxt/dist/app/components/server-placeholder")['default'],
    'LazyNuxtLink': typeof import("../node_modules/nuxt/dist/app/components/nuxt-link")['default']
  }
}
export const Avis: typeof import("../components/Avis.vue")['default']
export const CtaAvis: typeof import("../components/CtaAvis.vue")['default']
export const FullHero: typeof import("../components/FullHero.vue")['default']
export const GridHero: typeof import("../components/GridHero.vue")['default']
export const HIcon: typeof import("../components/HIcon.vue")['default']
export const ProductCard: typeof import("../components/ProductCard.vue")['default']
export const TFooter: typeof import("../components/TFooter.vue")['default']
export const TNavBar: typeof import("../components/TNavBar.vue")['default']
export const NuxtWelcome: typeof import("../node_modules/@nuxt/ui-templates/dist/templates/welcome.vue")['default']
export const NuxtLayout: typeof import("../node_modules/nuxt/dist/app/components/layout")['default']
export const NuxtErrorBoundary: typeof import("../node_modules/nuxt/dist/app/components/nuxt-error-boundary")['default']
export const ClientOnly: typeof import("../node_modules/nuxt/dist/app/components/client-only")['default']
export const ServerPlaceholder: typeof import("../node_modules/nuxt/dist/app/components/server-placeholder")['default']
export const NuxtLink: typeof import("../node_modules/nuxt/dist/app/components/nuxt-link")['default']
export const LazyAvis: typeof import("../components/Avis.vue")['default']
export const LazyCtaAvis: typeof import("../components/CtaAvis.vue")['default']
export const LazyFullHero: typeof import("../components/FullHero.vue")['default']
export const LazyGridHero: typeof import("../components/GridHero.vue")['default']
export const LazyHIcon: typeof import("../components/HIcon.vue")['default']
export const LazyProductCard: typeof import("../components/ProductCard.vue")['default']
export const LazyTFooter: typeof import("../components/TFooter.vue")['default']
export const LazyTNavBar: typeof import("../components/TNavBar.vue")['default']
export const LazyNuxtWelcome: typeof import("../node_modules/@nuxt/ui-templates/dist/templates/welcome.vue")['default']
export const LazyNuxtLayout: typeof import("../node_modules/nuxt/dist/app/components/layout")['default']
export const LazyNuxtErrorBoundary: typeof import("../node_modules/nuxt/dist/app/components/nuxt-error-boundary")['default']
export const LazyClientOnly: typeof import("../node_modules/nuxt/dist/app/components/client-only")['default']
export const LazyServerPlaceholder: typeof import("../node_modules/nuxt/dist/app/components/server-placeholder")['default']
export const LazyNuxtLink: typeof import("../node_modules/nuxt/dist/app/components/nuxt-link")['default']
export const componentNames: string[]
